mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', include('registration.urls')),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create/', views.QuestionCreateView.as_view(), name='create'),
]

mysite/registration/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True, help_text='The user who posted this question.')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/forms.py
from django import forms

from .models import Question, Choice

class QuestionCreateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']

class ChoiceCreateForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .forms import QuestionCreateForm, ChoiceCreateForm

from .models import Choice, Question

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['choice_form'] = ChoiceCreateForm()
        return context

    def post(self, request, pk):
        form = ChoiceCreateForm(request.POST)
        if form.is_valid:
            choice = form.save(commit=False)
            choice.question = Question.objects.get(pk=pk)
            choice.save()
            return HttpResponseRedirect(reverse('polls:detail', args=[pk]))
        # else if form is not valid
        context = {
          'choice_form': form,
          'question': Question.objects.get(pk=pk)
        }
        return render(request, 'polls/detail.html', context)


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class QuestionCreateView(LoginRequiredMixin, generic.edit.CreateView):
    login_url = reverse_lazy('login')

    def get(self, request, *args, **kwargs):
        context = {
          'form': QuestionCreateForm()
        }
        return render(request, 'polls/create.html', context)

    def post(self, request, *args, **kwargs):
        form = QuestionCreateForm(request.POST)
        if form.is_valid:
            question = form.save(commit=False) # don't save the question yet
            question.author = request.user
            question.save()
            return HttpResponseRedirect(
                reverse('polls:detail', args=[question.id]))
        # else if form is not valid
        return render(request, 'polls/create.html', { 'form': form })

mysite/polls/templates/polls/base.html
{% if request.user.is_authenticated %}
    <p align="left">
        Hello, {{ request.user.username }}!
    </p>
    <p align="right">
        <a href="/accounts/logout">Logout</a>
        <a href="/polls/create">New Poll</a>
    </p>

    {% else %}
    <p align="right">
        <a href="/registration/signup">Sign Up</a>
        <a href="/accounts/login">Login</a>
      </p>
{% endif %}

{% block content %}
<p>
    This is a placeholder block.
</p>
{% endblock %}

mysite/polls/templates/polls/create.html
{% extends 'polls/base.html' %}

{% block content %}
    <h3>New Poll</h3>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit">SUBMIT</button>
    </form>
    
{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>
    {% if question.author %}
        <p>Author: {{ question.author.username }}</p>
    {% endif %}

{% if request.user == question.author %}
    <!-- choice creation form -->
    <h3>Create a new Choice!</h3>
    <form method='POST'>
        {% csrf_token %}
        {{ choice_form.as_p }}

      <input type="submit" value="Submit new choice!">
    </form>
    {% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

{% endblock content %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock content %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock content %}